<?php

$counter_disabled = array();

$counter_disabled[] = 'cssjs';
$counter_disabled[] = 'captcha';
$counter_disabled[] = 'region_changer';
$counter_disabled[] = 'favicon.ico';
$counter_disabled[] = 'services.html';
$counter_disabled[] = 'pay';
$counter_disabled[] = 'rss.xml';
$counter_disabled[] = 'sitemap.xml';
$counter_disabled[] = 'redirect';
$counter_disabled[] = 'fav';
$counter_disabled[] = 'captcha';
$counter_disabled[] = 'messages_admin';
$counter_disabled[] = 'edit';
$counter_disabled[] = 'delete';

?>